---
- name: Configure /etc/wsl.conf
  become: true
  community.general.ini_file:
    path: /etc/wsl.conf
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    mode: "0644"
    no_extra_spaces: true
  loop:
    - section: network
      option: hostname
      value: "{{ wsl_hostname }}"
    - section: boot
      option: systemd
      value: "{{ wsl_systemd_enabled | lower }}"
    - section: interop
      option: appendWindowsPath
      value: "{{ wsl_append_windows_path | lower }}"
    - section: automount
      option: options
      value: "{{ wsl_automount_options }}"
  loop_control:
    label: "{{ item.section }}.{{ item.option }}"
  notify: Report wsl.conf change
