---
galaxy_info:
  author: drehtuer
  description: "git configuration for a WSL workstation"
  license: MIT
  min_ansible_version: "2.18"
  platforms:
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - wsl
    - workstation

dependencies: []
